# Implementing Hidden Layers

If we consider a normal classfiation problem such as classifying a red and blue points reguarding some criterial if the problem is linear we just have to draw one line. This can be achinved by a normal perspectron but imagine if the solution is a curve if we need to achieve this we need a more complex neural network. One way to go about this would be to combine two lines which means combining two pespectrons.

### Layer 1
Would be the input

### Layer 2 
Would recive the inputs calulate some function and apply an activation funciton on it and would go to next layer.

### Layer 3
Would recive the updated values with activation applied which would act as the weights to this layer and again would calulate some function to which also the activation function is applied and then this is given as output.

Here we are stacking up layer on top of layer which would allow the network to *learn* more complex patterns and hence we call this type of learning *deep learning*.

Let us consider a netork with three input layers, two hidden layers and one output layer.

The input would have weights which would be names as w<sub>ij</sub>

   Where ij is representing the dimestion of a matrix how?
Well let us consider the first input node it would have two weights w<sub>11</sub> and w<sub>12</sub>, which represents weights going from the input layer 1 to the hidden layer 1 ie.. w<sub>11</sub> and the weights going from input layer 1 to hidden layer 2 ie.. w<sub>12</sub>.

Similarly 

w<sub>21</sub> represents the weights going from input layer 2 to the hidden layer 1,
w<sub>22</sub> represents the weights going from input layer 2 to the hidden layer 2,
w<sub>31</sub> represents the weights going from input layer 3 to the hidden layer 1 and
w<sub>32</sub> represents the weights going from input layer 3 to the hidden layer 2.


In the previous notebook we were not able to represent this as a matrix but an array or vector now we can represent this as a 2d matrix

If we have the theory right we should be able to implement this in a 4x3x2 network

In [1]:
import numpy as np

In [4]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [5]:
#Network Size
N_input = 4
N_hidden = 3
N_output = 2

In [6]:
np.random.seed(42)

In [10]:
X = np.random.randn(4)
print(X)

[-0.23413696  1.57921282  0.76743473 -0.46947439]


Now we have out features X with 4 random values

In [12]:
weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
print(weights_input_to_hidden)

[[-0.02257763  0.00675282 -0.14247482]
 [-0.05443827  0.01109226 -0.11509936]
 [ 0.0375698  -0.06006387 -0.02916937]
 [-0.06017066  0.18522782 -0.00134972]]


In [13]:
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))
print(weights_hidden_to_output)

[[-0.10577109  0.08225449]
 [-0.12208436  0.02088636]
 [-0.19596701 -0.1328186 ]]


Now that we have all the weights required we are ready to make a foward pass through the network


In [17]:
hidden_layer_in = np.dot(X,weights_input_to_hidden)

We have done the foward pass and did a dot product between the features(X) and weights to the input layer now we need to apply sigmoid to this to find the output of the hidden layer

In [19]:
hidden_layer_out = sigmoid(hidden_layer_in)
print(hidden_layer_out)

[0.49409967 0.47075371 0.45756242]


Now we have the output a vector with 3 values Great

Lets find out the input to the output layer

In [20]:
output_layer_in = np.dot(hidden_layer_out,weights_hidden_to_output)

Now we did one more foward pass Let us calulate the output of the output layer by applying the sigmoid function

In [21]:
output_layer_out = sigmoid(output_layer_in)

In [22]:
print(output_layer_out)

[0.45031445 0.49742538]


_Great_ We have successfully implemented HiddenLayers